FROM python:3.11-slim

WORKDIR /opt/program

RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.inference.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.inference.txt

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PYTHONPATH="/opt/program"

COPY src/ src/

EXPOSE 8080

ENTRYPOINT ["python", "src/predict.py"]